apiVersion: "admissionregistration.k8s.io/v1"
kind: "MutatingWebhookConfiguration"
metadata:
  name: {{ include "common.name" . | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "webhook"
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ tpl .Values.certManager.certificate.name . }}"
  {{- end }}
webhooks:
  -
    name: "mdeployment.kb.io"
    failurePolicy: "Fail"
    sideEffects: "None"
    admissionReviewVersions:
      - "v1"
    clientConfig:
      service:
        name: {{ include "common.name" . | quote }}
        namespace: {{ .Release.Namespace | quote }}
        path: "/mutate-v1-deployment"
    rules:
      -
        apiGroups:
          - "apps"
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
          - "UPDATE"
        resources:
          - "deployments"
  -
    name: "mstatefulset.kb.io"
    failurePolicy: "Fail"
    sideEffects: "None"
    admissionReviewVersions:
      - "v1"
    clientConfig:
      service:
        name: {{ include "common.name" . | quote }}
        namespace: {{ .Release.Namespace | quote }}
        path: "/mutate-v1-statefulset"
    rules:
      -
        apiGroups:
          - "apps"
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
          - "UPDATE"
        resources:
          - "statefulsets"
  -
    name: "mjob.kb.io"
    failurePolicy: "Fail"
    sideEffects: "None"
    admissionReviewVersions:
      - "v1"
    clientConfig:
      service:
        name: {{ include "common.name" . | quote }}
        namespace: {{ .Release.Namespace | quote }}
        path: "/mutate-v1-job"
    rules:
      -
        apiGroups:
          - "batch"
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
          - "UPDATE"
        resources:
          - "jobs"
