apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "common.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "webhook"
spec:
  ports:
    -
      port: 443
      targetPort: 9443
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
