{{ if .Values.serviceAccount.create -}}
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "rbac"
{{- end }}
